"""Paraphrased problem summaries.

These summaries are written in original wording (no verbatim LeetCode prompt text).
"""

SUMMARIES = {
    "0001": "Given an array of integers and a target, return indices of two distinct elements whose sum equals the target.",
    "0002": "Add two non-negative integers represented by linked lists in reverse digit order and return the sum as a linked list in the same format.",
    "0003": "Find the length of the longest substring of a string that contains no repeated characters.",
    "0004": "Given two sorted arrays, compute the median of the combined multiset in better than linear time.",
    "0005": "Find the longest contiguous substring of a string that reads the same forward and backward.",
    "0006": "Write the string in a zigzag pattern across a given number of rows and read it row-by-row to form the converted string.",
    "0009": "Determine whether an integer reads the same forward and backward without converting it to a string (where possible).",
    "0011": "Given heights of vertical lines, choose two lines to maximize the area of water they can contain.",
    "0012": "Convert an integer into its Roman numeral representation using standard subtractive rules.",
    "0013": "Convert a Roman numeral string into its integer value, handling subtractive pairs correctly.",
    "0014": "Given a list of strings, return the longest prefix shared by all of them (or empty if none).",
    "0017": "Given digits from 2–9, generate all possible letter strings based on the classic phone keypad mapping.",
    "0019": "Remove the n-th node from the end of a singly linked list and return the head of the modified list.",
    "0020": "Check whether a string of brackets is properly balanced and correctly nested.",
    "0021": "Merge two sorted linked lists into a single sorted linked list.",
    "0022": "Generate all valid combinations of n pairs of parentheses.",
    "0023": "Merge k sorted linked lists into one sorted list.",
    "0024": "Swap every two adjacent nodes in a linked list and return the new head without changing node values.",
    "0026": "Remove duplicates in-place from a sorted array so each element appears once, returning the new length.",
    "0027": "Remove all instances of a given value from an array in-place and return the length of the remaining prefix.",
    "0029": "Compute integer division of two 32-bit signed integers without using multiplication, division, or modulo, clamping to 32-bit range.",
    "0031": "Rearrange numbers into the next lexicographically greater permutation; if none exists, transform into the smallest permutation.",
    "0033": "Search for a target value in a rotated sorted array and return its index or -1 in logarithmic time.",
    "0034": "In a sorted array, find the starting and ending indices of a target value, or return [-1, -1] if absent.",
    "0035": "Return the index where a target should be inserted in a sorted array to keep it ordered.",
    "0038": "Produce the n-th term of the 'count and say' sequence by describing the previous term's runs of digits.",
    "0039": "Given candidate numbers (reusable) and a target, list all unique combinations that sum to the target.",
    "0046": "Return all possible permutations of a list of distinct integers.",
    "0048": "Rotate an n×n matrix 90 degrees clockwise in-place.",
    "0049": "Group strings into sets where each set contains words that are anagrams of each other.",
    "0053": "Find the maximum possible sum of a non-empty contiguous subarray.",
    "0055": "Given jump lengths from each index, determine if you can reach the final index starting from the first.",
    "0056": "Given intervals, merge all that overlap and return the resulting set of disjoint intervals.",
    "0066": "Given a non-negative integer represented as an array of digits, add one and return the resulting digits.",
    "0067": "Add two binary strings and return the sum as a binary string.",
    "0069": "Compute the integer square root of a non-negative integer (the floor of the true square root).",
    "0070": "Count how many distinct ways you can climb to the top if you can take 1 or 2 steps at a time.",
    "0072": "Compute the minimum number of single-character edits (insert, delete, replace) to transform one string into another.",
    "0074": "Determine whether a target exists in a matrix where rows are sorted and each row starts after the previous row ends.",
    "0075": "Sort an array containing only 0s, 1s, and 2s in-place (three-way partition).",
    "0078": "Return all subsets (the power set) of a list of distinct integers.",
    "0079": "Check if a given word can be formed in a grid by moving horizontally/vertically without reusing a cell.",
    "0088": "Merge two sorted arrays into the first one in-place, given that it has enough trailing space.",
    "0091": "Given a digit string, count the number of ways to decode it into letters using 1→A through 26→Z.",
    "0094": "Return the inorder traversal of a binary tree's node values.",
    "0100": "Determine whether two binary trees are structurally identical and have equal values at all corresponding nodes.",
    "0102": "Return the level-order (breadth-first) traversal of a binary tree as a list of levels.",
    "0107": "Return the level-order traversal of a binary tree from bottom level up to the root level.",
    "0118": "Generate the first n rows of Pascal’s triangle.",
    "0121": "Given daily stock prices, compute the maximum profit from exactly one buy followed by one sell (or 0 if none).",
    "0122": "Compute the maximum profit from as many stock trades as you like, but you must sell before buying again.",
    "0125": "Check if a string is a palindrome when considering only letters/digits and ignoring case.",
    "0131": "Partition a string into all possible lists of substrings such that every substring in the partition is a palindrome.",
    "0136": "In an array where every element appears twice except one, find the unique element using bitwise reasoning.",
    "0138": "Create a deep copy of a linked list where each node has both next and random pointers.",
    "0141": "Detect whether a linked list contains a cycle.",
    "0143": "Reorder a linked list to interleave from the ends inward: first, last, second, second-last, and so on.",
    "0144": "Return the preorder traversal of a binary tree's node values.",
    "0145": "Return the postorder traversal of a binary tree's node values.",
    "0151": "Reverse the order of words in a string, collapsing extra spaces so words are separated by single spaces.",
    "0152": "Find the maximum product of a non-empty contiguous subarray.",
    "0153": "Find the minimum element in a rotated sorted array in logarithmic time.",
    "0155": "Design a stack supporting push, pop, top, and retrieving the current minimum in constant time.",
    "0160": "Given two singly linked lists, find the node where they intersect (by reference), or return None if they do not.",
    "0169": "Find the element that appears more than half the time in an array (guaranteed to exist).",
    "0172": "Compute how many trailing zeros are in n! by counting factors of 5.",
    "0189": "Rotate an array to the right by k steps in-place (or with minimal extra space).",
    "0191": "Count the number of set bits (1s) in the binary representation of an unsigned integer.",
    "0198": "Given non-negative values in houses along a street, maximize stolen amount without robbing adjacent houses.",
    "0202": "Repeatedly replace a number by the sum of squares of its digits; determine if it eventually reaches 1.",
    "0203": "Remove all nodes with a given value from a linked list and return the new head.",
    "0204": "Count how many prime numbers are strictly less than n.",
    "0205": "Determine if two strings are isomorphic by checking whether characters map consistently in both directions.",
    "0206": "Reverse a singly linked list and return the new head.",
    "0208": "Implement a trie supporting insertion, full-word search, and prefix checking.",
    "0217": "Determine whether an array contains any duplicate value.",
    "0219": "Check whether the same value appears at two indices whose difference is at most k.",
    "0225": "Implement a LIFO stack using only queue operations.",
    "0226": "Invert a binary tree by swapping left and right children for every node.",
    "0227": "Evaluate a basic arithmetic expression with non-negative integers and +, -, *, / respecting operator precedence.",
    "0230": "Find the k-th smallest value in a binary search tree.",
    "0231": "Determine whether an integer is a power of two.",
    "0232": "Implement a FIFO queue using only stack operations.",
    "0234": "Determine whether a linked list’s values form a palindrome sequence.",
    "0237": "Delete a node from a singly linked list when only that node is given (not the head).",
    "0238": "For each index, return the product of all numbers in the array except the one at that index, without using division.",
    "0242": "Determine whether two strings contain the same character counts (i.e., are anagrams).",
    "0258": "Repeatedly sum the digits of a number until one digit remains and return it (digital root).",
    "0268": "Given numbers from 0..n with one missing, find the missing value.",
    "0278": "Using an API that tells whether a version is bad, find the first bad version with minimal calls.",
    "0283": "Move all zeros in an array to the end while maintaining the relative order of non-zero elements.",
    "0287": "Given n+1 integers with values in 1..n and one value repeated, find the duplicate without modifying the array (ideally).",
    "0292": "Given n stones where players remove 1–3 each turn, determine if the first player has a winning strategy.",
    "0322": "Given coin denominations and an amount, return the fewest coins needed to make that amount (or -1 if impossible).",
    "0328": "Rearrange a linked list so nodes in odd positions come first, followed by nodes in even positions, preserving relative order within each group.",
    "0344": "Reverse an array of characters in-place.",
    "0345": "Reverse only the vowels in a string while keeping other characters in their original positions.",
    "0347": "Return the k most frequent elements in an array.",
    "0349": "Compute the set intersection of two arrays, returning unique common elements.",
    "0350": "Compute the intersection of two arrays including multiplicities (each element appears as many times as it appears in both).",
    "0367": "Determine whether a positive integer is a perfect square without using built-in square root functions.",
    "0371": "Compute the sum of two integers without using + or - by using bitwise operations.",
    "0373": "Given two sorted arrays, find the k pairs (one from each array) with the smallest sums.",
    "0383": "Determine if a ransom note string can be constructed from the letters available in a magazine string.",
    "0385": "Parse a string representing a nested list of integers into a nested structure (NestedInteger).",
    "0387": "Find the index of the first character in a string that appears exactly once, or -1 if none exists.",
    "0392": "Determine whether one string is a subsequence of another (characters in order, not necessarily contiguous).",
    "0402": "Remove exactly k digits from a non-negative integer string to produce the smallest possible resulting number string.",
    "0412": "Produce the classic FizzBuzz list for numbers 1..n based on divisibility by 3 and 5.",
    "0443": "Compress a character array in-place using run-length encoding and return the new length.",
    "0448": "Given an array of integers in 1..n, find which numbers in that range do not appear in the array.",
    "0451": "Reorder characters in a string so that characters with higher frequency come first.",
    "0463": "Given a 0/1 grid representing land and water, compute the perimeter of the island cells.",
    "0476": "Compute the bitwise complement of a positive integer over its significant bits.",
    "0496": "For each element in nums1, find its next greater element to the right in nums2 (or -1 if none).",
    "0500": "Return the words that can be typed using letters from only one row of a standard keyboard layout.",
    "0503": "For each element in a circular array, find the next greater element when scanning forward (wrapping around).",
    "0525": "Find the maximum length of a contiguous subarray with equal numbers of 0s and 1s.",
    "0540": "In a sorted array where every element appears twice except one, find the single element in logarithmic time.",
    "0543": "Compute the diameter of a binary tree (the maximum number of edges on any path between two nodes).",
    "0557": "Reverse the characters of each word in a sentence while keeping word order and spaces intact.",
    "0560": "Count how many contiguous subarrays sum to k.",
    "0605": "Given a flowerbed array and n new flowers, determine if n flowers can be planted without adjacent flowers.",
    "0617": "Merge two binary trees by summing overlapping node values and keeping non-null branches where only one tree has nodes.",
    "0657": "Given moves on a 2D grid, determine if the robot returns to the origin.",
    "0665": "Determine whether an array can become non-decreasing by modifying at most one element.",
    "0674": "Find the length of the longest contiguous strictly increasing segment in an array.",
    "0678": "Given a string with '(', ')', and '*', determine if it can be a valid parenthesis string where '*' can act as '(', ')', or empty.",
    "0692": "Return the k most frequent words, breaking ties by lexicographic order.",
    "0700": "Search for a given value in a binary search tree and return the subtree rooted at that node (or None).",
    "0704": "Perform binary search on a sorted array to find a target index or -1 if missing.",
    "0705": "Design a hash set without using built-in hash set libraries, supporting add, remove, and contains.",
    "0707": "Design a linked list with operations like get, add at head/tail/index, and delete at index.",
    "0709": "Convert all uppercase letters in a string to lowercase.",
    "0724": "Find an index where the sum of elements to the left equals the sum of elements to the right (pivot index).",
    "0733": "Perform a flood fill on an image grid, recoloring the connected region starting at a given cell.",
    "0739": "For each day’s temperature, compute how many days you must wait to see a warmer temperature (or 0 if none).",
    "0771": "Count how many stones are jewels given strings describing jewel types and stones you have.",
    "0844": "Compare two strings after applying backspace operations where '#' deletes the previous character.",
    "0849": "Given seats as 0/1, choose an empty seat to maximize distance to the closest occupied seat.",
    "0852": "Given an array that increases then decreases, find the index of the peak element using logarithmic time.",
    "0856": "Compute the score of a balanced parentheses string using the specified scoring rules based on nesting and concatenation.",
    "0872": "Determine whether two binary trees have identical sequences of leaf values from left to right.",
    "0876": "Return the middle node of a linked list (if even length, return the second middle).",
    "0881": "Given people’s weights and a boat limit, find the minimum number of boats needed if each boat carries at most two people.",
    "0890": "Find which words match a pattern by a consistent one-to-one letter mapping.",
    "0929": "Normalize email addresses by ignoring dots in the local name and ignoring anything after '+'; count unique normalized addresses.",
    "0941": "Determine whether an array forms a valid mountain: strictly increasing to one peak then strictly decreasing.",
    "0961": "In an array of size 2N where exactly one value repeats N times, find that repeated value.",
    "0981": "Design a time-based key-value store supporting set(key, value, timestamp) and get(key, timestamp) returning the latest value at or before the timestamp.",
    "0993": "Determine whether two nodes in a binary tree are cousins (same depth but different parents).",
    "0997": "In a town where the judge trusts nobody and everyone else trusts the judge, identify the judge from trust pairs (or report none).",
    "1014": "Given sightseeing values, maximize score of i<j defined by values[i] + values[j] + i - j.",
    "1021": "Remove the outermost parentheses from every primitive balanced substring in a parentheses string.",
    "1029": "Send exactly N people to each of two cities with minimum total cost given per-person costs for each city.",
    "1046": "Repeatedly smash the two heaviest stones; if unequal, the remainder is put back—return the final remaining weight (or 0).",
    "1047": "Repeatedly remove adjacent equal characters from a string until no more removals are possible.",
    "1051": "Count how many indices differ between the original heights array and its sorted version.",
    "1108": "Replace '.' with '[.]' in an IP address string to produce a defanged version.",
    "1137": "Compute the n-th Tribonacci number with base values T0=0, T1=1, T2=1.",
    "1160": "Given words and available characters, sum lengths of words that can be formed using the characters with limited counts.",
    "1189": "Given letters in a string, compute how many times the word 'balloon' can be formed.",
    "1207": "Determine whether the frequencies of values in an array are all distinct.",
    "1281": "For an integer, compute (product of digits) minus (sum of digits).",
    "1317": "Split an integer n into two positive integers whose decimal representations contain no zero digits.",
    "1356": "Sort integers by the count of 1 bits in their binary form, breaking ties by numeric value.",
    "1360": "Compute the number of days between two dates given as YYYY-MM-DD.",
    "1362": "Find two integers whose product is n+1 or n+2 and whose absolute difference is minimized.",
    "1366": "Rank teams based on multiple vote strings, comparing vote counts position-by-position with alphabetical tie-breakers.",
    "1370": "Reorder characters by repeatedly taking the smallest available increasing run, then the largest available decreasing run, until exhausted.",
    "1374": "Construct a string of length n using lowercase letters such that every character used appears an odd number of times.",
    "1380": "Find all matrix entries that are the minimum in their row and simultaneously the maximum in their column.",
    "1399": "Group numbers 1..n by the sum of their digits and return how many groups have the largest size.",
    "1400": "Determine whether a string’s characters can be rearranged into exactly k non-empty palindrome strings.",
    "1401": "Determine whether a circle overlaps (intersects or touches) an axis-aligned rectangle on a 2D plane.",
    "1426": "Count elements x in an array such that x+1 is also present in the array (counting each occurrence of x).",
    "1427": "Apply a sequence of left/right shift operations to a string and return the final string.",
    "1431": "For each child’s candies, determine if they could have the greatest count after receiving some extra candies.",
    "1432": "Maximize the difference between two numbers formed by replacing digits consistently in the original number (choose replacements for max and min).",
    "1433": "Determine whether one string can 'break' another after rearranging both, meaning it is >= at every position in sorted order (or vice versa).",
    "1480": "Compute the running prefix sum array where each element is the sum of all elements up to that index.",
    "1991": "Find the leftmost index where the sum of elements to the left equals the sum of elements to the right (middle index).",
}
